site_name: "Markdown Exec"
site_description: "Utilities to execute code blocks in Markdown files."
site_url: "https://pawamoy.github.io/markdown-exec"
repo_url: "https://github.com/pawamoy/markdown-exec"
repo_name: "pawamoy/markdown-exec"
site_dir: "site"

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- Usage: usage.md
- Gallery: gallery.md
# defer to gen-files + literate-nav
- Code Reference: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md
- Author's website: https://pawamoy.github.io/

theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
  - navigation.tabs
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
- callouts:
    strip_period: false
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
    base_path: [docs/snippets, "."]
- pymdownx.highlight
- pymdownx.superfences:
    custom_fences:
    - name: python
      class: python
      validator: !!python/name:markdown_exec.validator
      format: !!python/name:markdown_exec.formatter
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.md
- coverage
- section-index
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        selection:
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
        rendering:
          show_submodules: no
          # docstring_section_style: list
          members_order: alphabetical
          show_category_heading: no
          merge_init_into_class: yes
    watch:
    - src/markdown_exec

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/pawamoy
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/pawamoy
